"""empty message

Revision ID: da93a3c2020f
Revises: 
Create Date: 2020-04-12 14:31:50.090209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da93a3c2020f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_post',
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=True),
    sa.Column('boxAddress', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('firstName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_post')
    # ### end Alembic commands ###
